pluginManagement { repositories { maven { url = 'https://maven.minecraftforge.net' }; gradlePluginPortal(); mavenCentral() } }
dependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS); repositories { maven { url = 'https://maven.minecraftforge.net' }; mavenCentral() } }
rootProject.name = 'shine-backport-1.20.1-forge'
